name: flutter_class
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Iconos estilo iOS
  cupertino_icons: ^1.0.8

  # Plugins externos
  location: ^6.0.2        # Para GPS
  image_picker: ^1.1.2    # Para cámara/galería
  flutter_speech: ^2.0.1   # Ejemplo de plugin alternativo

  # speech_to_text: ^6.6.2  # Para micrófono

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
